imports:
    - { resource: ../common/config.yml }
    - { resource: parameters.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/dev/routing.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    delivery_address: tuanquynh0508@gmail.com

nelmio_api_doc:
    name: NG2 CMS API
    sandbox:
        #endpoint:
        authentication:
            delivery: http
            name: Authorization
            type: bearer
        body_format:
            formats: [ json, form ]
            default_format: json
        request_format:
            formats:
                json: application/json
                xml: application/xml
            method: accept_header
            default_format: json
