services:
    #Logger
    app.service.client_logger:
        class: ApiBundle\Service\ClientLogService
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: client }

    #Validate
    app.constraint.validator.unique_field:
        class: ApiBundle\Validator\Constraints\UniqueFieldValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: validator.unique }

    app.validator.base:
        class: ApiBundle\Validator\BaseValidator
        #abstract: true
        calls:
            - [setValidator, ["@validator"]]

    app.validator.user:
        class: ApiBundle\Validator\UserValidator
        parent: app.validator.base
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    app.validator.log:
        class: ApiBundle\Validator\LogValidator
        parent: app.validator.base

    #Security
    app.security.api_user_provider:
        class: ApiBundle\Security\User\ApiUserProvider
        arguments: ["@doctrine.orm.entity_manager"]

    app.security.api_authenticator:
        class:     ApiBundle\Security\ApiAuthenticator
        arguments: ["@security.password_encoder", "@translator"]

    #Event Listener
    app.event.locale_listener:
        class:   ApiBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - {name: kernel.event_subscriber}

    app.event.exception_listener:
        class: ApiBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
